//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LpsScriptParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Lunalipse.Core.BehaviorScript.ScriptV3.SyntaxParser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LpsScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ILpsScriptParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.prg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrg([NotNull] LpsScriptParser.PrgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.prg_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrg_start([NotNull] LpsScriptParser.Prg_startContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.prg_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrg_end([NotNull] LpsScriptParser.Prg_endContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.prg_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrg_content([NotNull] LpsScriptParser.Prg_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] LpsScriptParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.statements_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements_loop([NotNull] LpsScriptParser.Statements_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.if_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_branch([NotNull] LpsScriptParser.If_branchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.else_branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_branch([NotNull] LpsScriptParser.Else_branchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.if_branch_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_branch_loop([NotNull] LpsScriptParser.If_branch_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.else_branch_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_branch_loop([NotNull] LpsScriptParser.Else_branch_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop([NotNull] LpsScriptParser.LoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.declares"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclares([NotNull] LpsScriptParser.DeclaresContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare([NotNull] LpsScriptParser.DeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.declare_ids"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_ids([NotNull] LpsScriptParser.Declare_idsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LpsScriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.statement_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_loop([NotNull] LpsScriptParser.Statement_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.cata_choose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCata_choose([NotNull] LpsScriptParser.Cata_chooseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.play_actions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlay_actions([NotNull] LpsScriptParser.Play_actionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.set_eqzr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_eqzr([NotNull] LpsScriptParser.Set_eqzrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.do_action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDo_action([NotNull] LpsScriptParser.Do_actionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.group_statemnt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_statemnt([NotNull] LpsScriptParser.Group_statemntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SuffixLoop</c>
	/// labeled alternative in <see cref="LpsScriptParser.loop_act"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffixLoop([NotNull] LpsScriptParser.SuffixLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SuffixSetVol</c>
	/// labeled alternative in <see cref="LpsScriptParser.volume_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffixSetVol([NotNull] LpsScriptParser.SuffixSetVolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.conditions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditions([NotNull] LpsScriptParser.ConditionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] LpsScriptParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] LpsScriptParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.expr_wrap"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_wrap([NotNull] LpsScriptParser.Expr_wrapContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprInd</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprInd([NotNull] LpsScriptParser.ExprIndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprP4</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprP4([NotNull] LpsScriptParser.ExprP4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprParen</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprParen([NotNull] LpsScriptParser.ExprParenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprP3</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprP3([NotNull] LpsScriptParser.ExprP3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprP6</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprP6([NotNull] LpsScriptParser.ExprP6Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprP5</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprP5([NotNull] LpsScriptParser.ExprP5Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprUnary</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprUnary([NotNull] LpsScriptParser.ExprUnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprP2</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprP2([NotNull] LpsScriptParser.ExprP2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exprP1</c>
	/// labeled alternative in <see cref="LpsScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprP1([NotNull] LpsScriptParser.ExprP1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] LpsScriptParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.array_indexing"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_indexing([NotNull] LpsScriptParser.Array_indexingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayDeclr</c>
	/// labeled alternative in <see cref="LpsScriptParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclr([NotNull] LpsScriptParser.ArrayDeclrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.array_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_content([NotNull] LpsScriptParser.Array_contentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.any"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny([NotNull] LpsScriptParser.AnyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.any_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_id([NotNull] LpsScriptParser.Any_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.any_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_number([NotNull] LpsScriptParser.Any_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] LpsScriptParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P0([NotNull] LpsScriptParser.Optr_P0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P1([NotNull] LpsScriptParser.Optr_P1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P2([NotNull] LpsScriptParser.Optr_P2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P3([NotNull] LpsScriptParser.Optr_P3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P4([NotNull] LpsScriptParser.Optr_P4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P5([NotNull] LpsScriptParser.Optr_P5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LpsScriptParser.optr_P6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptr_P6([NotNull] LpsScriptParser.Optr_P6Context context);
}
} // namespace Lunalipse.Core.BehaviorScript.ScriptV3.SyntaxParser
